development:
  adapter: postgresql
  database: photogram_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: photogram_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: photogram_production
  pool: 5
  timeout: 5000
